version: 2.1

orbs:
  stack-build: pbrisbin/stack-build@3.0.0
  docker-build-cached: pbrisbin/docker-build-cached@1.0.0
  aws-cli: circleci/aws-cli@1.2.1
  pushover: pbrisbin/pushover@1.0.0

jobs:
  update-stack-image:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Update CloudFormation Stack
          command: |
            image=restyled/restyler:${CIRCLE_SHA1:0:10}
            aws cloudformation update-stack \
              --stack-name prod-services \
              --use-previous-template \
              --parameter "ParameterKey=Environment,UsePreviousValue=true" \
              --parameter "ParameterKey=RestyledImage,UsePreviousValue=true" \
              --parameter "ParameterKey=AppsWebhooksDesiredCount,UsePreviousValue=true" \
              --parameter "ParameterKey=RestylerImage,ParameterValue=$image" \
              --capabilities CAPABILITY_NAMED_IAM
            aws cloudformation wait stack-update-complete \
              --stack-name prod-services

references:
  master_only: &master_only
    filters:
      branches:
        only:
          - master

workflows:
  build_and_release:
    jobs:
      - stack-build/build-test-lint:
          name: build
          hlint-yaml-url:
            https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml

      - docker-build-cached/build-and-release:
          name: image
          registry-username: DOCKERHUB_USERNAME
          registry-password: DOCKERHUB_PASSWORD
          image: restyled/restyler
          build-stages: builder
          extra-build-arguments: '--build-arg "REVISION=$CIRCLE_SHA1"'

      - update-stack-image:
          <<: *master_only
          name: release
          requires: [build, image]
          context: deploy-aws

      - pushover/notify:
          <<: *master_only
          name: notify
          requires:
            - release
          title: 'Restyled deployments'
          message: 'restyler deployed at ${CIRCLE_SHA1:0:10}'
