version: 2.0

jobs:
  build:
    docker:
      - image: quay.io/haskell_works/stack-build-minimal
        environment:
          GIT_AUTHOR_EMAIL: ci@restyled.io
          GIT_AUTHOR_NAME: Restyled.io CI
          GIT_COMMITTER_EMAIL: ci@restyled.io
          GIT_COMMITTER_NAME: Restyled.io CI
          STACK_ARGUMENTS: --no-terminal
    steps:
      - checkout
      - run:
          name: Digest
          command: git ls-files | xargs md5sum > digest
      - restore_cache:
          keys:
            # yamllint disable-line rule:line-length
            - v2-{{ .Branch }}-{{ checksum "stack.yaml" }}-{{ checksum "digest" }}
            - v2-{{ .Branch }}-{{ checksum "stack.yaml" }}-
            - v2-{{ .Branch }}
            - v2-
      - run:
          name: Upgrade Stack
          command: stack upgrade
      - run:
          name: Dependencies
          command: |
            make setup setup.lint
            curl "$HLINT_YAML_SRC" > .hlint.yaml
          environment:
            # yamllint disable-line rule:line-length
            HLINT_YAML_SRC: https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml
      - run:
          name: Build
          command: make build
      - save_cache:
          # yamllint disable-line rule:line-length
          key: v2-{{ .Branch }}-{{ checksum "stack.yaml" }}-{{ checksum "digest" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Test
          command: make test
      - run:
          name: Lint
          command: make lint

  image:
    docker:
      - image: quay.io/restyled-io/ops
    steps:
      - checkout
      - setup_remote_docker:
         docker_layer_caching: true
      - run:
          name: Build
          command: |
            release_tag=b$CIRCLE_BUILD_NUM
            release_image=quay.io/restyled-io/restyler

            mkdir -p workspace
            echo "$release_tag" > workspace/release-tag
            echo "$release_image" > workspace/release-image

            docker build --tag "${release_image}:${release_tag}" .
            docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io
            docker push "${release_image}:${release_tag}"
      - persist_to_workspace:
          root: workspace
          paths:
            - release-tag
            - release-image

  release:
    docker:
      - image: quay.io/restyled-io/ops
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Release
          command: |
            read -r release_tag < /tmp/workspace/release-tag
            read -r release_image < /tmp/workspace/release-image

            heroku config:set --app restyled-io \
              "RESTYLER_TAG=$release_tag" \
              "RESTYLER_IMAGE=$release_image"

            notify "restyled-io[restyler]" "Deploy of $release_tag successful"

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - image:
          filters:
            branches:
              only:
                - master
      - release:
          requires:
            - build
            - image
          filters:
            branches:
              only:
                - master
