---
version: 2.0

jobs:
  build_and_test:
    docker:
      - image: fpco/stack-build:lts
        environment:
          GIT_AUTHOR_EMAIL: ci@restyled.io
          GIT_AUTHOR_NAME: Restyled.io CI
          GIT_COMMITTER_EMAIL: ci@restyled.io
          GIT_COMMITTER_NAME: Restyled.io CI
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
            - stack-{{ .Branch }}
            - stack-
      - run:
          name: Dependencies
          command: make setup
      - run:
          name: Build
          command: make build
      - run:
          name: Lint
          command: make lint
      - save_cache:
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Test
          command: make test.ci

  deploy:
    docker:
      - image: docker:17.07.0-ce
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          version: 17.07.0-ce
      - run:
          name: Dependencies
          command: apk add --update git make
      - run:
          name: Build image
          command: |
            if git show --no-patch | grep -Fq ':nodeploy:'; then
              echo "HEAD commit included :nodeploy:, skipping..."
              exit 0
            fi

            make image.build
      - deploy:
          name: Docker Hub
          command: |
            if git show --no-patch | grep -Fq ':nodeploy:'; then
              echo "HEAD commit included :nodeploy:, skipping..."
              exit 0
            fi

            if [[ "$CIRCLE_BRANCH" == master ]]; then
              docker login \
                --username "$DOCKERHUB_USERNAME" \
                --password "$DOCKERHUB_PASSWORD"

              make image.release
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          context: org-global
          requires:
            - build_and_test
